# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: zed_dset_yolov5/images/  # dataset root dir
train: zed_dset_yolov5/images/autosplit_train.txt  # train images (relative to 'path')
val: zed_dset_yolov5/images/autosplit_val.txt  # val images (relative to 'path')
test: zed_dset_yolov5/images/test/ # test images (optional)

# Classes
nc: 2  # number of classes
names: [ 'boat', 'obstacle' ]  # class names
